---
- name: Configure webserver with apache
  hosts: webservers
  become: true
  gather_facts: false
     
  tasks:   
    - name: Install apache
      apt: name=apache2 state=present update_cache=yes

    - name: Change server timezone
      command: timedatectl set-timezone Africa/Lagos

    - name: create simple index file for apache
      shell: echo "<h1> Thank you for visiting Server $(hostname). Todays date is $(date) </h1>" > /var/www/html/index.html

    - name: restart apache2
      service: name=apache2 state=restarted

